version: "3.9"

networks:
  my_network:

services:
  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:3.7.0'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
    networks:
      - my_network

  kafka:
    container_name: kafka
    image: 'bitnami/kafka:2.8.0'
    ports:
      - '9092:9092'
    networks:
      - my_network
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    expose:
      - '9092'
    depends_on:
      - zookeeper

  producer:
    container_name: producer
    build: ./Producer
    networks:
      - my_network
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    depends_on:
      - kafka
      - zookeeper
  
  consumerventas:
    container_name: consumerventas
    build: ./Ventas
    networks:
      - my_network
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
    depends_on:
      - kafka
      - zookeeper
      - producer

  consumerstock:
    container_name: consumerstock
    build: ./Stock
    networks:
      - my_network
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5001:5001"
    depends_on:
      - kafka
      - zookeeper
      - producer

  consumerposicion:
    container_name: consumerposicion
    build: ./Posicion
    networks:
      - my_network
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5002:5002"
    depends_on:
      - kafka
      - zookeeper
      - producer

  consumermiembro:
    container_name: consumermiembro
    build: ./Miembro
    networks:
      - my_network
    ports:
      - "5003:5003"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - kafka
      - zookeeper
      - producer

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    ports:
     - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - kafka
    networks:
      - my_network